{
 "title": "Host overview",
 "tags": [ "hosts" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Host metrics timeline",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (job) (last_over_time(up{host!=\"\",exporter=\"\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job, host) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{job}} / {{host}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (max by (job, host) (node_memory_MemAvailable_bytes) / max by (job, host) (node_memory_MemTotal_bytes))) * 100",
     "legendFormat": "{{job}} / {{host}}"
    }
   ]
  },
  {
   "title": "Root filesystem usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (max by (job, host) (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!~\"tmpfs|fuse.lxcfs|overlay|parsecfs|squashfs\"}) / max by (job, host) (node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|fuse.lxcfs|overlay|parsecfs|squashfs\"}))) * 100",
     "legendFormat": "{{job}} / {{host}} /"
    }
   ]
  }
 ]
}